#!/bin/bash
mkdir /home/wyna/scripts
mkdir /home/wyna/notes
mkdir /home/wyna/downloads
mv ../install /home/wyna/scripts/install

mv /home/wyna/scripts/install/sources.list /etc/apt/sources.list
apt update

apt install -y debfoster 
apt install -y sudo vim tmux git
apt install -y elinks fim
debfoster
