#!/bin/bash
mv /home/wyna/deb-setup/* /home/wyna/
rm -r /home/wyna/deb-setup
mkdir /home/wyna/scripts
mkdir /home/wyna/notes
mkdir /home/wyna/downloads

mv /home/wyna/scripts/install/sources.list /etc/apt/sources.list
apt update

apt install -y debfoster 
apt install -y sudo vim tmux man
apt install -y elinks fim
debfoster
